# Generated by Django 5.0.6 on 2025-07-25 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=75, verbose_name="Название фирмы"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта фирмы"
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=75, verbose_name="Страна фирмы"),
                ),
                ("city", models.CharField(max_length=75, verbose_name="Город фирмы")),
                ("street", models.CharField(max_length=75, verbose_name="Улица фирмы")),
                ("house_number", models.PositiveIntegerField(verbose_name="Дом фирмы")),
            ],
            options={
                "verbose_name": "Контакты Фирмы",
                "verbose_name_plural": "Контакты фирмы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Название")),
                ("model", models.CharField(max_length=75, verbose_name="Модель")),
                (
                    "date_of_market_launch",
                    models.DateField(verbose_name="дата выхода на рынок"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Название")),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_contacts",
                        to="shops.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="factory_Product",
                        to="shops.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завод",
                "verbose_name_plural": "Заводы",
            },
        ),
        migrations.CreateModel(
            name="RetailNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Название")),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=13,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Задолженность перед поставщиком с точностью до копеек",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retail_network_contacts",
                        to="shops.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="retail_network_Product",
                        to="shops.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_network_provider",
                        to="shops.factory",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розничная сеть",
                "verbose_name_plural": "Розничные сети",
            },
        ),
        migrations.CreateModel(
            name="IndividualEntrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Название")),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=13,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Задолженность перед поставщиком с точностью до копеек",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_entrepreneur_contacts",
                        to="shops.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "provider_factory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_entrepreneur_provider_factory",
                        to="shops.factory",
                        verbose_name="Поставщик с завода",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="individual_entrepreneur_Product",
                        to="shops.product",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "provider_retail_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_entrepreneur_provider_retail_network",
                        to="shops.retailnetwork",
                        verbose_name="Поставщик с розничной сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный предприниматель",
                "verbose_name_plural": "Индивидуальные предприниматели",
            },
        ),
    ]
